// common/errorCodes.js
module.exports = {
  DUPLICATE_ID: 'DUPLICATE_ID',
  NOT_FOUND: 'NOT_FOUND',
  ENTITY_VALIDATION_FAILED: 'VALIDATION_FAILED',
  BUSINESS_LOGIC_FAILED: 'BUSINESS_LOGIC_FAILED',
  INVALID_ID: 'INVALID_ID',
  DB_ERROR: 'DB_ERROR'
  // ...add more as needed
};